// Clean local static server for Fight World 2.3.7
"use strict";
const fs=require("fs"),path=require("path"),http=require("http"),cp=require("child_process");
const HOST="127.0.0.1",PORT=5187,ROOT=process.cwd();
if(!fs.existsSync(path.join(ROOT,"index.html"))||!fs.existsSync(path.join(ROOT,"reset-cache.html")))throw new Error("Run from repository root after apply-update-button-hard-reset-2.3.7.cjs");
const mime={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".cjs":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json; charset=utf-8",".webmanifest":"application/manifest+json; charset=utf-8",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".svg":"image/svg+xml",".ico":"image/x-icon",".txt":"text/plain; charset=utf-8"};
function safe(url){let clean=decodeURIComponent(String(url||"/").split("?")[0]);if(clean==="/"||clean==="")clean="/index.html";clean=clean.replace(/^\/+/,"");const full=path.resolve(ROOT,clean);return full.startsWith(ROOT)?full:null}
const server=http.createServer((req,res)=>{try{const full=safe(req.url||"/");if(!full||!fs.existsSync(full)||!fs.statSync(full).isFile()){res.writeHead(404,{"Content-Type":"text/plain; charset=utf-8","Cache-Control":"no-store"});res.end("404");return}const ext=path.extname(full).toLowerCase();res.writeHead(200,{"Content-Type":mime[ext]||"application/octet-stream","Cache-Control":"no-store, no-cache, must-revalidate, max-age=0","Pragma":"no-cache","Expires":"0"});fs.createReadStream(full).pipe(res)}catch(e){res.writeHead(500,{"Content-Type":"text/plain; charset=utf-8","Cache-Control":"no-store"});res.end(String(e&&e.stack?e.stack:e))}});
server.listen(PORT,HOST,()=>{const url=`http://${HOST}:${PORT}/reset-cache.html?start=clean&t=${Date.now()}`;console.log("Clean Fight World local server:");console.log("  "+url);console.log("");console.log("Press Ctrl+C to stop.");if(process.platform==="win32")cp.spawn("cmd",["/c","start","",url],{detached:true,stdio:"ignore"}).unref();else if(process.platform==="darwin")cp.spawn("open",[url],{detached:true,stdio:"ignore"}).unref();else cp.spawn("xdg-open",[url],{detached:true,stdio:"ignore"}).unref();});
