var PRO_CAREER_DATA = {
  contenderStatuses: [
    { id: "unsigned", label: "Без проф. статуса", minWins: 0, minRankingSeed: 0 },
    { id: "debutant", label: "Дебютант", minWins: 0, minRankingSeed: 4 },
    { id: "low_card", label: "Нижняя часть карда", minWins: 1, minRankingSeed: 10 },
    { id: "prospect", label: "Проспект", minWins: 3, minRankingSeed: 22 },
    { id: "ranked", label: "Рейтинговый боец", minWins: 6, minRankingSeed: 42 },
    { id: "eliminator_ready", label: "На пороге элиминатора", minWins: 9, minRankingSeed: 68 },
    { id: "title_path", label: "Рядом с титульным боем", minWins: 12, minRankingSeed: 96 }
  ],
  reputationTags: [
    { id: "ex_national_team", label: "Бывший сборник" },
    { id: "ex_olympian", label: "Олимпийская база" },
    { id: "street_star", label: "Уличная звезда" },
    { id: "failed_amateur_talent", label: "Не раскрывшийся любитель" },
    { id: "hometown_draw", label: "Локальное имя" }
  ],
  promoterTemplates: [
    {
      id: "small_hall",
      label: "Зальный промоутер",
      purseBonus: 0,
      fameBonus: 0,
      travelBias: 0,
      pressure: 8,
      badContractShift: 0,
      explanation: "Даёт первые проф. бои рядом с домом."
    },
    {
      id: "city_booker",
      label: "Городской промоутер",
      purseBonus: 12,
      fameBonus: 1,
      travelBias: 1,
      pressure: 12,
      badContractShift: 4,
      explanation: "Выводит на городские площадки и делает путь шире."
    },
    {
      id: "regional_push",
      label: "Региональный промоутер",
      purseBonus: 24,
      fameBonus: 2,
      travelBias: 2,
      pressure: 18,
      badContractShift: 8,
      explanation: "Двигает на выездные бои и поднимает гонорары."
    },
    {
      id: "tv_slot",
      label: "ТВ-промоутер",
      purseBonus: 38,
      fameBonus: 4,
      travelBias: 3,
      pressure: 24,
      badContractShift: 12,
      explanation: "Даёт заметные бои, но любит плотный график."
    },
    {
      id: "major_house",
      label: "Крупный промоутер",
      purseBonus: 55,
      fameBonus: 6,
      travelBias: 4,
      pressure: 30,
      badContractShift: 16,
      explanation: "Открывает большой путь, но давит сильнее всех."
    }
  ],
  managerTemplates: [
    {
      id: "starter_manager",
      label: "Менеджер старта",
      purseBonus: 4,
      winBonus: 2,
      koBonus: 2,
      rankingBoost: 2,
      travelGuard: 1,
      pressureGuard: 1,
      explanation: "Простой менеджер для первого шага в профи."
    },
    {
      id: "careful_manager",
      label: "Осторожный менеджер",
      purseBonus: 8,
      winBonus: 4,
      koBonus: 3,
      rankingBoost: 3,
      travelGuard: 2,
      pressureGuard: 3,
      explanation: "Старается вести аккуратно и без лишнего риска."
    },
    {
      id: "growth_manager",
      label: "Менеджер роста",
      purseBonus: 12,
      winBonus: 6,
      koBonus: 5,
      rankingBoost: 6,
      travelGuard: 2,
      pressureGuard: 4,
      explanation: "Хорошо ведёт бойца от дебюта к нормальным боям."
    },
    {
      id: "hard_negotiator",
      label: "Жёсткий переговорщик",
      purseBonus: 18,
      winBonus: 8,
      koBonus: 7,
      rankingBoost: 7,
      travelGuard: 3,
      pressureGuard: 5,
      explanation: "Выбивает деньги, но любит плотный график."
    },
    {
      id: "big_office",
      label: "Большой офис",
      purseBonus: 26,
      winBonus: 12,
      koBonus: 10,
      rankingBoost: 10,
      travelGuard: 4,
      pressureGuard: 7,
      explanation: "Даёт сильную упаковку и быстрый доступ к рейтингу."
    }
  ],
  offerTemplates: [
    {
      id: "pro_debut",
      label: "Профессиональный дебют",
      trackId: "pro",
      pipelineStage: "debut",
      tier: "safe",
      travel: "home",
      purseBase: 110,
      winBonus: 35,
      koBonus: 25,
      fameBase: 8,
      toxicBase: 10,
      declineRep: -1,
      acceptRep: 2,
      promoterPressure: 8,
      travelRisk: 4,
      badContractRisk: 10,
      minAge: 18,
      minProWins: 0,
      minRankingSeed: 0,
      explanationId: "debut"
    },
    {
      id: "pro_low_card",
      label: "Бой в нижней части карда",
      trackId: "pro",
      pipelineStage: "low_card",
      tier: "safe",
      travel: "home",
      purseBase: 150,
      winBonus: 45,
      koBonus: 32,
      fameBase: 11,
      toxicBase: 14,
      declineRep: -1,
      acceptRep: 3,
      promoterPressure: 12,
      travelRisk: 6,
      badContractRisk: 14,
      minAge: 18,
      minProWins: 1,
      minRankingSeed: 8,
      explanationId: "low_card"
    },
    {
      id: "pro_prospect",
      label: "Бой проспекта",
      trackId: "pro",
      pipelineStage: "prospect",
      tier: "even",
      travel: "away",
      purseBase: 210,
      winBonus: 65,
      koBonus: 48,
      fameBase: 15,
      toxicBase: 18,
      declineRep: -2,
      acceptRep: 4,
      promoterPressure: 18,
      travelRisk: 12,
      badContractRisk: 18,
      minAge: 18,
      minProWins: 2,
      minRankingSeed: 18,
      explanationId: "prospect"
    },
    {
      id: "pro_ranking_fight",
      label: "Рейтинговый бой",
      trackId: "pro",
      pipelineStage: "ranking",
      tier: "even",
      travel: "away",
      purseBase: 300,
      winBonus: 95,
      koBonus: 75,
      fameBase: 22,
      toxicBase: 24,
      declineRep: -3,
      acceptRep: 5,
      promoterPressure: 24,
      travelRisk: 18,
      badContractRisk: 24,
      minAge: 19,
      minProWins: 5,
      minRankingSeed: 40,
      explanationId: "ranking"
    },
    {
      id: "pro_eliminator_placeholder",
      label: "Бой за шаг до элиминатора",
      trackId: "pro",
      pipelineStage: "eliminator",
      tier: "danger",
      travel: "away",
      purseBase: 430,
      winBonus: 135,
      koBonus: 110,
      fameBase: 30,
      toxicBase: 28,
      declineRep: -4,
      acceptRep: 6,
      promoterPressure: 32,
      travelRisk: 22,
      badContractRisk: 28,
      minAge: 20,
      minProWins: 8,
      minRankingSeed: 64,
      explanationId: "eliminator"
    },
    {
      id: "pro_title_path_placeholder",
      label: "Бой на титульном пути",
      trackId: "pro",
      pipelineStage: "title_path",
      tier: "danger",
      travel: "away",
      purseBase: 620,
      winBonus: 190,
      koBonus: 150,
      fameBase: 42,
      toxicBase: 34,
      declineRep: -5,
      acceptRep: 7,
      promoterPressure: 38,
      travelRisk: 28,
      badContractRisk: 32,
      minAge: 21,
      minProWins: 11,
      minRankingSeed: 92,
      explanationId: "title_path"
    }
  ],
  explanationTexts: {
    debut: "Первый бой в профи. Тебя проверяют на спокойном уровне.",
    low_card: "Тебя ставят в ранний кард, чтобы посмотреть на продажи и работу в ринге.",
    prospect: "Твой ход уже заметили. Это шанс закрепиться как проспект.",
    ranking: "Есть шанс подняться в рейтинге и выйти на более серьёзные имена.",
    eliminator: "Почти элитный уровень. Победа двигает к большому отбору.",
    title_path: "Большой шанс рядом. Ошибка здесь больно откатывает назад."
  },
  transitionRules: {
    amateurMinAge: 18,
    amateurMinRankId: "adult_class_2",
    amateurMinScore: 145,
    streetMinAge: 18,
    streetMinRating: 105,
    streetMinFame: 18,
    exNationalTeamSeedBonus: 18,
    reserveNationalTeamSeedBonus: 10,
    olympicSeedBonus: 30,
    olympicRankSeedBonus: 20,
    streetStarSeedBonus: 14,
    hometownDrawSeedBonus: 8,
    failedAmateurPenalty: -6
  }
};
