var WORLD_FACILITY_DATA = {
  gymTypes: [
    { id: "street", label: "Уличная база" },
    { id: "youth", label: "Юниорская школа" },
    { id: "amateur", label: "Любительский зал" },
    { id: "regional_center", label: "Региональный центр" },
    { id: "national_team_base", label: "База сборной" },
    { id: "pro", label: "Профессиональный клуб" },
    { id: "mixed", label: "Смешанный лагерь" }
  ],
  trainerTypes: [
    { id: "youth", label: "Юниорский тренер" },
    { id: "amateur", label: "Любительский тренер" },
    { id: "elite_amateur", label: "Старший любительский тренер" },
    { id: "national_team", label: "Тренер сборной" },
    { id: "street", label: "Уличный тренер" },
    { id: "pro", label: "Профессиональный тренер" }
  ],
  gymTemplates: [
    {
      slot: 1,
      slug: "youth_school",
      label: "Юниорская школа",
      gymType: "youth",
      orgType: "youth_boxing_school",
      cost: 15,
      reputation: 28,
      minRankId: "",
      allowedTracks: ["amateur"],
      trainerSlots: [1, 2],
      trainingBonuses: { trainingPoints: 1, recoveryHealth: 1, safeBias: 1 },
      developmentProfile: { focusBoosts: { technique: 1, endurance: 1 }, styleWeights: { outboxer: 1, tempo: 1 } }
    },
    {
      slot: 2,
      slug: "amateur_section",
      label: "Любительская секция",
      gymType: "amateur",
      orgType: "amateur_gym",
      cost: 35,
      reputation: 40,
      minRankId: "junior_class_3",
      allowedTracks: ["amateur"],
      trainerSlots: [2, 3],
      trainingBonuses: { trainingPoints: 2, recoveryHealth: 1, safeBias: 1 },
      developmentProfile: { focusBoosts: { technique: 1, defense: 1 }, styleWeights: { outboxer: 1, counterpuncher: 1 } }
    },
    {
      slot: 3,
      slug: "amateur_hall",
      label: "Сильный зал",
      gymType: "amateur",
      orgType: "amateur_gym",
      cost: 60,
      reputation: 52,
      minRankId: "junior_class_2",
      allowedTracks: ["amateur"],
      trainerSlots: [3, 4],
      trainingBonuses: { trainingPoints: 3, fameBonus: 1, purseBonus: 2, safeBias: 1 },
      developmentProfile: { focusBoosts: { technique: 2, defense: 1 }, styleWeights: { outboxer: 1, counterpuncher: 1, tempo: 1 } }
    },
    {
      slot: 4,
      slug: "regional_center",
      label: "Региональный центр",
      gymType: "regional_center",
      orgType: "regional_amateur_center",
      cost: 100,
      reputation: 68,
      minRankId: "adult_class_3",
      allowedTracks: ["amateur"],
      trainerSlots: [4, 5],
      trainingBonuses: { trainingPoints: 4, recoveryHealth: 2, fameBonus: 2, safeBias: 2 },
      developmentProfile: { focusBoosts: { endurance: 1, defense: 1, technique: 1 }, styleWeights: { tempo: 1, outboxer: 1, counterpuncher: 1 } }
    },
    {
      slot: 5,
      slug: "national_base",
      label: "Центр сборной",
      gymType: "national_team_base",
      orgType: "national_team",
      cost: 150,
      reputation: 84,
      minRankId: "candidate_national",
      allowedTracks: ["amateur", "pro"],
      trainerSlots: [5, 7],
      trainingBonuses: { trainingPoints: 5, recoveryHealth: 2, fameBonus: 3, purseBonus: 5, toxicGuard: 3, safeBias: 2 },
      developmentProfile: { focusBoosts: { technique: 2, defense: 1, recovery: 1 }, styleWeights: { outboxer: 1, counterpuncher: 1, tempo: 1 } }
    },
    {
      slot: 6,
      slug: "street_base",
      label: "Районная база",
      gymType: "street",
      orgType: "district_scene",
      cost: 20,
      reputation: 32,
      minRankId: "",
      allowedTracks: ["street"],
      trainerSlots: [6, 7],
      trainingBonuses: { trainingPoints: 2, purseBonus: 4, koBonus: 6 },
      developmentProfile: { focusBoosts: { power: 1, sparring: 1 }, styleWeights: { puncher: 1, tempo: 1 } }
    },
    {
      slot: 7,
      slug: "mixed_camp",
      label: "Смешанный лагерь",
      gymType: "mixed",
      orgType: "mixed",
      cost: 110,
      reputation: 60,
      minRankId: "adult_class_2",
      allowedTracks: ["street", "amateur", "pro"],
      trainerSlots: [4, 7, 8],
      trainingBonuses: { trainingPoints: 4, recoveryHealth: 2, purseBonus: 6, toxicGuard: 2 },
      developmentProfile: { focusBoosts: { power: 1, technique: 1, recovery: 1 }, styleWeights: { puncher: 1, counterpuncher: 1, tempo: 1 } }
    },
    {
      slot: 8,
      slug: "pro_club",
      label: "Профессиональный клуб",
      gymType: "pro",
      orgType: "promotion",
      cost: 150,
      reputation: 88,
      minRankId: "adult_class_1",
      allowedTracks: ["pro"],
      trainerSlots: [7, 8],
      trainingBonuses: { trainingPoints: 5, recoveryHealth: 2, fameBonus: 3, purseBonus: 10, koBonus: 14, toxicGuard: 4 },
      developmentProfile: { focusBoosts: { power: 2, technique: 1, defense: 1, recovery: 1 }, styleWeights: { puncher: 1, outboxer: 1, counterpuncher: 1 } }
    }
  ],
  trainerTemplates: [
    {
      slot: 1,
      slug: "youth_trainer",
      trainerType: "youth",
      coachRoleId: "youth_trainer",
      salary: 15,
      minRankId: "",
      gymSlot: 1,
      allowedTracks: ["amateur"],
      preferredStyles: ["outboxer", "tempo"],
      specialization: ["техника", "база"],
      bonuses: { trainingPoints: 1, recoveryHealth: 1 },
      developmentProfile: { focusBoosts: { technique: 1 }, styleWeights: { outboxer: 1 } }
    },
    {
      slot: 2,
      slug: "amateur_trainer_1",
      trainerType: "amateur",
      coachRoleId: "amateur_trainer",
      salary: 35,
      minRankId: "junior_class_3",
      gymSlot: 2,
      allowedTracks: ["amateur"],
      preferredStyles: ["outboxer", "counterpuncher"],
      specialization: ["любительская база", "ритм"],
      bonuses: { trainingPoints: 2, recoveryHealth: 1, stressRelief: 1 },
      developmentProfile: { focusBoosts: { endurance: 1, defense: 1 }, styleWeights: { tempo: 1, counterpuncher: 1 } }
    },
    {
      slot: 3,
      slug: "amateur_trainer_2",
      trainerType: "amateur",
      coachRoleId: "amateur_trainer",
      salary: 60,
      minRankId: "junior_class_2",
      gymSlot: 3,
      allowedTracks: ["amateur"],
      preferredStyles: ["outboxer", "tempo"],
      specialization: ["объем", "школа"],
      bonuses: { trainingPoints: 3, fameBonus: 1, safeBias: 1 },
      developmentProfile: { focusBoosts: { technique: 2, defense: 1 }, styleWeights: { outboxer: 1, tempo: 1 } }
    },
    {
      slot: 4,
      slug: "elite_amateur_coach",
      trainerType: "elite_amateur",
      coachRoleId: "elite_amateur_coach",
      salary: 100,
      minRankId: "adult_class_3",
      gymSlot: 4,
      allowedTracks: ["amateur"],
      preferredStyles: ["counterpuncher", "tempo", "outboxer"],
      specialization: ["сильная группа", "спарринги"],
      bonuses: { trainingPoints: 4, recoveryHealth: 1, purseBonus: 5, toxicGuard: 2 },
      developmentProfile: { focusBoosts: { endurance: 1, technique: 1, defense: 1 }, styleWeights: { counterpuncher: 1, tempo: 1 } }
    },
    {
      slot: 5,
      slug: "national_team_coach",
      trainerType: "national_team",
      coachRoleId: "national_team_coach",
      salary: 150,
      minRankId: "candidate_national",
      gymSlot: 5,
      allowedTracks: ["amateur", "pro"],
      preferredStyles: ["outboxer", "counterpuncher"],
      specialization: ["сборная", "пик формы"],
      bonuses: { trainingPoints: 5, fameBonus: 2, recoveryHealth: 2, toxicGuard: 4 },
      developmentProfile: { focusBoosts: { technique: 2, defense: 1, recovery: 1 }, styleWeights: { outboxer: 1, counterpuncher: 1 } }
    },
    {
      slot: 6,
      slug: "street_trainer",
      trainerType: "street",
      coachRoleId: "street_trainer",
      salary: 20,
      minRankId: "",
      gymSlot: 6,
      allowedTracks: ["street"],
      preferredStyles: ["puncher", "tempo"],
      specialization: ["жесткие бои", "улица"],
      bonuses: { trainingPoints: 2, purseBonus: 4, koBonus: 8 },
      developmentProfile: { focusBoosts: { power: 1, sparring: 1 }, styleWeights: { puncher: 1, tempo: 1 } }
    },
    {
      slot: 7,
      slug: "mixed_coach",
      trainerType: "pro",
      coachRoleId: "pro_trainer",
      salary: 110,
      minRankId: "adult_class_2",
      gymSlot: 7,
      allowedTracks: ["street", "amateur", "pro"],
      preferredStyles: ["puncher", "counterpuncher", "tempo"],
      specialization: ["лагерь", "переход между треками"],
      bonuses: { trainingPoints: 4, recoveryHealth: 2, purseBonus: 7, koBonus: 10, toxicGuard: 3 },
      developmentProfile: { focusBoosts: { power: 1, technique: 1, recovery: 1 }, styleWeights: { puncher: 1, counterpuncher: 1 } }
    },
    {
      slot: 8,
      slug: "pro_coach",
      trainerType: "pro",
      coachRoleId: "pro_trainer",
      salary: 150,
      minRankId: "adult_class_1",
      gymSlot: 8,
      allowedTracks: ["pro"],
      preferredStyles: ["puncher", "outboxer", "counterpuncher"],
      specialization: ["большие бои", "профи"],
      bonuses: { trainingPoints: 5, recoveryHealth: 2, fameBonus: 3, purseBonus: 10, koBonus: 16, toxicGuard: 5 },
      developmentProfile: { focusBoosts: { power: 2, technique: 1, defense: 1, recovery: 1 }, styleWeights: { puncher: 1, outboxer: 1, counterpuncher: 1 } }
    }
  ]
};
