var YOUTH_AMATEUR_DATA = (function () {
  var amateurRankLabels = {
    "default": {
      junior_novice: "Юниор-новичок",
      junior_class_3: "Юниорский класс III",
      junior_class_2: "Юниорский класс II",
      junior_class_1: "Юниорский класс I",
      adult_class_3: "Взрослый класс III",
      adult_class_2: "Взрослый класс II",
      adult_class_1: "Взрослый класс I",
      candidate_national: "Кандидат в сборную",
      national_master: "Национальный мастер",
      international_master: "Международный мастер",
      national_team_candidate: "Кандидат в нац. команду",
      national_team_member: "Член нац. команды",
      olympic_level: "Олимпийский уровень"
    },
    "russia": {
      junior_novice: "Юный новичок",
      junior_class_3: "III юношеский разряд",
      junior_class_2: "II юношеский разряд",
      junior_class_1: "I юношеский разряд",
      adult_class_3: "III взрослый разряд",
      adult_class_2: "II взрослый разряд",
      adult_class_1: "I взрослый разряд",
      candidate_national: "КМС",
      national_master: "МС",
      international_master: "МСМК",
      national_team_candidate: "Кандидат в сборную",
      national_team_member: "Сборная страны",
      olympic_level: "Олимпийский уровень"
    },
    "usa": {
      junior_novice: "Junior Novice",
      junior_class_3: "Junior Class C",
      junior_class_2: "Junior Class B",
      junior_class_1: "Junior Class A",
      adult_class_3: "Senior Class C",
      adult_class_2: "Senior Class B",
      adult_class_1: "Senior Class A",
      candidate_national: "National Prospect",
      national_master: "National Master",
      international_master: "International Master",
      national_team_candidate: "Team Candidate",
      national_team_member: "National Team",
      olympic_level: "Olympic Level"
    },
    "mexico": {
      junior_novice: "Novato juvenil",
      junior_class_3: "Juvenil clase III",
      junior_class_2: "Juvenil clase II",
      junior_class_1: "Juvenil clase I",
      adult_class_3: "Clase nacional III",
      adult_class_2: "Clase nacional II",
      adult_class_1: "Clase nacional I",
      candidate_national: "Preseleccion",
      national_master: "Maestro nacional",
      international_master: "Maestro internacional",
      national_team_candidate: "Candidato al equipo",
      national_team_member: "Seleccion nacional",
      olympic_level: "Nivel olimpico"
    },
    "cuba": {
      junior_novice: "Escuela inicial",
      junior_class_3: "Juvenil nivel III",
      junior_class_2: "Juvenil nivel II",
      junior_class_1: "Juvenil nivel I",
      adult_class_3: "Clase nacional III",
      adult_class_2: "Clase nacional II",
      adult_class_1: "Clase nacional I",
      candidate_national: "Preseleccion",
      national_master: "Maestro nacional",
      international_master: "Maestro internacional",
      national_team_candidate: "Candidato al equipo",
      national_team_member: "Equipo nacional",
      olympic_level: "Nivel olimpico"
    },
    "japan": {
      junior_novice: "Юниор 4 кю",
      junior_class_3: "Юниор 3 кю",
      junior_class_2: "Юниор 2 кю",
      junior_class_1: "Юниор 1 кю",
      adult_class_3: "Сеньор 3 кю",
      adult_class_2: "Сеньор 2 кю",
      adult_class_1: "Сеньор 1 кю",
      candidate_national: "Кандидат страны",
      national_master: "Национальный мастер",
      international_master: "Международный мастер",
      national_team_candidate: "Кандидат в сборную",
      national_team_member: "Сборная Японии",
      olympic_level: "Олимпийский уровень"
    },
    "china": {
      junior_novice: "Юниор начального уровня",
      junior_class_3: "Юниор III класса",
      junior_class_2: "Юниор II класса",
      junior_class_1: "Юниор I класса",
      adult_class_3: "Взрослый III класса",
      adult_class_2: "Взрослый II класса",
      adult_class_1: "Взрослый I класса",
      candidate_national: "Кандидат в пров. сборную",
      national_master: "Национальный мастер",
      international_master: "Международный мастер",
      national_team_candidate: "Кандидат в сборную",
      national_team_member: "Сборная страны",
      olympic_level: "Олимпийский уровень"
    },
    "uk": {
      junior_novice: "Junior Novice",
      junior_class_3: "Junior Class C",
      junior_class_2: "Junior Class B",
      junior_class_1: "Junior Class A",
      adult_class_3: "Senior Class C",
      adult_class_2: "Senior Class B",
      adult_class_1: "Senior Class A",
      candidate_national: "National Prospect",
      national_master: "National Elite",
      international_master: "International Elite",
      national_team_candidate: "GB Candidate",
      national_team_member: "GB Squad",
      olympic_level: "Olympic Level"
    },
    "philippines": {
      junior_novice: "Junior Novice",
      junior_class_3: "Junior Class III",
      junior_class_2: "Junior Class II",
      junior_class_1: "Junior Class I",
      adult_class_3: "Senior Class III",
      adult_class_2: "Senior Class II",
      adult_class_1: "Senior Class I",
      candidate_national: "National Prospect",
      national_master: "National Master",
      international_master: "International Master",
      national_team_candidate: "National Pool",
      national_team_member: "National Team",
      olympic_level: "Olympic Level"
    }
  };

  return {
    agePhases: [
      {
        id: "junior_phase",
        label: "Юниорский этап",
        minAge: 16,
        maxAge: 17,
        primary: true,
        adultSandbox: false,
        summary: "Поддержка семьи или зала, юниорские старты и мягкий быт."
      },
      {
        id: "adult_entry",
        label: "Вход во взрослый бокс",
        minAge: 18,
        maxAge: 20,
        primary: true,
        adultSandbox: true,
        summary: "Открывается взрослый цикл карьеры, но любительская база еще очень важна."
      },
      {
        id: "amateur_peak_window",
        label: "Пик любителя",
        minAge: 18,
        maxAge: 28,
        primary: false,
        adultSandbox: true,
        summary: "Лучшее время для разрядов, отборов и сборной."
      },
      {
        id: "pro_prime",
        label: "Прайм взрослого бойца",
        minAge: 22,
        maxAge: 33,
        primary: false,
        adultSandbox: true,
        summary: "Возраст, в котором легче держать пик формы и идти выше."
      },
      {
        id: "decline",
        label: "Спад",
        minAge: 34,
        maxAge: 60,
        primary: true,
        adultSandbox: true,
        summary: "Тело требует больше внимания, ошибки стоят дороже."
      }
    ],
    livingModes: [
      {
        id: "family",
        label: "С семьей",
        weeklyCost: 0,
        weeklyStress: -2,
        weeklyMorale: 3,
        weeklyWear: -1,
        recoveryHealthBonus: 4,
        recoveryStressRelief: 2,
        disciplineBonus: 4,
        supportBonus: 4,
        summary: "Стабильная поддержка и спокойный режим."
      },
      {
        id: "shared_dorm",
        label: "Общага",
        weeklyCost: 5,
        weeklyStress: 1,
        weeklyMorale: 0,
        weeklyWear: 0,
        recoveryHealthBonus: 1,
        recoveryStressRelief: 0,
        disciplineBonus: 1,
        supportBonus: 1,
        summary: "Дешево и терпимо, но без тишины."
      },
      {
        id: "gym_corner",
        label: "Угол в зале",
        weeklyCost: 10,
        weeklyStress: 2,
        weeklyMorale: -1,
        weeklyWear: 1,
        recoveryHealthBonus: 0,
        recoveryStressRelief: -1,
        disciplineBonus: 6,
        supportBonus: 0,
        trainerSupportBonus: 1,
        gymSupportBonus: 1,
        summary: "Жестко, зато все рядом с рингом."
      }
    ],
    amateurRanks: [
      { id: "junior_novice", order: 0, minAge: 16, minScore: 0, unlockSummary: "Первые юниорские старты." },
      { id: "junior_class_3", order: 1, minAge: 16, minScore: 20, unlockSummary: "Клубные юниорские бои." },
      { id: "junior_class_2", order: 2, minAge: 16, minScore: 48, unlockSummary: "Сильные юниорские сетки и хорошие секции." },
      { id: "junior_class_1", order: 3, minAge: 16, minScore: 82, unlockSummary: "Крупные юниорские турниры." },
      { id: "adult_class_3", order: 4, minAge: 18, minScore: 120, unlockSummary: "Взрослые любительские бои." },
      { id: "adult_class_2", order: 5, minAge: 18, minScore: 165, unlockSummary: "Региональные турниры и сильные тренеры." },
      { id: "adult_class_1", order: 6, minAge: 18, minScore: 220, unlockSummary: "Крупные взрослые старты." },
      { id: "candidate_national", order: 7, minAge: 18, minScore: 290, unlockSummary: "Отборы на уровень страны." },
      { id: "national_master", order: 8, minAge: 18, minScore: 380, unlockSummary: "Элитный уровень и путь к сборной." },
      { id: "international_master", order: 9, minAge: 18, minScore: 470, unlockSummary: "Международные старты." },
      { id: "national_team_candidate", order: 10, minAge: 18, minScore: 560, unlockSummary: "Предбанник национальной команды." },
      { id: "national_team_member", order: 11, minAge: 18, minScore: 660, unlockSummary: "Место в национальной команде." },
      { id: "olympic_level", order: 12, minAge: 18, minScore: 780, unlockSummary: "Олимпийский уровень." }
    ],
    rankLabelsByCountry: amateurRankLabels,
    juniorSupportModel: {
      familySupportBonus: 2,
      trainerSupportBonus: 1,
      gymSupportBonus: 1,
      reducedWeeklyObligation: 10
    },
    amateurFightOfferTemplates: [
      {
        id: "junior_club_card",
        label: "Юниорский клубный бой",
        travel: "home",
        tier: "safe",
        trackId: "amateur",
        minAge: 16,
        maxAge: 17,
        minRankId: "junior_novice",
        purseBase: 18,
        winBonus: 6,
        koBonus: 4,
        fameBase: 2,
        toxicBase: 0,
        declineRep: 0,
        acceptRep: 1,
        rankPointsWin: 8,
        rankPointsLoss: 2,
        rankPointsDraw: 5,
        opponentQualityBase: 6
      },
      {
        id: "junior_open",
        label: "Юниорский открытый турнир",
        travel: "home",
        tier: "even",
        trackId: "amateur",
        minAge: 16,
        maxAge: 17,
        minRankId: "junior_class_3",
        purseBase: 24,
        winBonus: 8,
        koBonus: 6,
        fameBase: 3,
        toxicBase: 0,
        declineRep: -1,
        acceptRep: 2,
        rankPointsWin: 12,
        rankPointsLoss: 3,
        rankPointsDraw: 7,
        opponentQualityBase: 10
      },
      {
        id: "junior_regional",
        label: "Юниорский региональный турнир",
        travel: "away",
        tier: "even",
        trackId: "amateur",
        minAge: 16,
        maxAge: 17,
        minRankId: "junior_class_2",
        purseBase: 32,
        winBonus: 12,
        koBonus: 8,
        fameBase: 5,
        toxicBase: 2,
        declineRep: -1,
        acceptRep: 3,
        rankPointsWin: 16,
        rankPointsLoss: 4,
        rankPointsDraw: 9,
        opponentQualityBase: 14
      },
      {
        id: "adult_amateur_class",
        label: "Взрослый любительский бой",
        travel: "home",
        tier: "safe",
        trackId: "amateur",
        minAge: 18,
        minRankId: "adult_class_3",
        purseBase: 42,
        winBonus: 16,
        koBonus: 10,
        fameBase: 6,
        toxicBase: 2,
        declineRep: -1,
        acceptRep: 2,
        rankPointsWin: 18,
        rankPointsLoss: 5,
        rankPointsDraw: 10,
        opponentQualityBase: 16
      },
      {
        id: "adult_regional_cup",
        label: "Региональный кубок",
        travel: "away",
        tier: "even",
        trackId: "amateur",
        minAge: 18,
        minRankId: "adult_class_2",
        purseBase: 55,
        winBonus: 20,
        koBonus: 14,
        fameBase: 8,
        toxicBase: 4,
        declineRep: -1,
        acceptRep: 3,
        rankPointsWin: 24,
        rankPointsLoss: 6,
        rankPointsDraw: 12,
        opponentQualityBase: 22
      },
      {
        id: "national_selection_cup",
        label: "Отборочный турнир",
        travel: "away",
        tier: "danger",
        trackId: "amateur",
        minAge: 18,
        minRankId: "adult_class_1",
        purseBase: 72,
        winBonus: 28,
        koBonus: 18,
        fameBase: 11,
        toxicBase: 6,
        declineRep: -2,
        acceptRep: 4,
        rankPointsWin: 32,
        rankPointsLoss: 8,
        rankPointsDraw: 16,
        opponentQualityBase: 28
      },
      {
        id: "national_team_trial",
        label: "Просмотр в сборную",
        travel: "away",
        tier: "danger",
        trackId: "amateur",
        minAge: 18,
        minRankId: "candidate_national",
        purseBase: 90,
        winBonus: 36,
        koBonus: 24,
        fameBase: 14,
        toxicBase: 8,
        declineRep: -3,
        acceptRep: 5,
        rankPointsWin: 42,
        rankPointsLoss: 10,
        rankPointsDraw: 20,
        opponentQualityBase: 36
      }
    ],
    adultTransitionEvent: {
      id: "adult_transition_18",
      title: "Тебе исполнилось 18",
      text: "Юниорский этап позади. Теперь ты входишь во взрослую часть карьеры, где выборов больше и цена ошибок выше."
    }
  };
}());
