(function(){
'use strict';
var VERSION='gameplay-update-fix-2.3.8',SCHEMA=238;
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function forceVersion(){window.FS=window.FS||{};window.FS.Data=window.FS.Data||{};window.FS.Data.appVersion=VERSION;window.FS.Data.saveSchemaVersion=SCHEMA;}
function clearCaches(){if(!window.caches||!caches.keys)return Promise.resolve();return caches.keys().then(function(keys){return Promise.all(keys.map(function(k){var low=String(k).toLowerCase();return(low.includes('fight')||low.includes('simulator')||low.indexOf('fw-')===0)?caches.delete(k):false;}));});}
function unregisterSW(){if(!('serviceWorker'in navigator)||!navigator.serviceWorker.getRegistrations)return Promise.resolve();return navigator.serviceWorker.getRegistrations().then(function(regs){return Promise.all(regs.map(function(r){return r.unregister();}));});}
function hardUpdate(e){if(e){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();}try{localStorage.setItem('fightWorldUpdateTarget',VERSION);}catch(_e){}unregisterSW().then(clearCaches).then(function(){location.replace('./reset-cache.html?update=2.3.8&t='+Date.now());}).catch(function(){location.replace('./reset-cache.html?update=2.3.8&t='+Date.now());});return false;}
function installUpdateFix(){if(window.__fwUpdateFix238)return;window.__fwUpdateFix238=true;['click','touchend','pointerup'].forEach(function(type){document.addEventListener(type,function(e){var b=e.target&&e.target.closest?e.target.closest('button'):null;if(!b)return;var text=(b.textContent||'').toLowerCase();if(b.classList.contains('update-now-btn')||b.dataset.updateNow||b.dataset.action==='force-update'||text.indexOf('обновить')!==-1)return hardUpdate(e);},true);});}
function R(){return{U:(window.FS&&window.FS.Utils)||{},F:(window.FS&&window.FS.Fight)||{},D:(window.FS&&window.FS.Data)||{}};}
function byId(state,id){var r=R();if(!state||!id)return null;if(r.U.getFighterById)return r.U.getFighterById(state,id);return(state.roster||[]).find(function(f){return f&&f.id===id;})||null;}
function nm(f){return f?(f.name||f.fullName||((f.firstName||'')+' '+(f.lastName||f.surname||'')).trim()||'Боец'):'Боец';}
function ovr(f){var r=R();if(!f)return 0;if(r.U.statAverage)return r.U.statAverage(f.stats||f);return Math.round(Number(f.ovr||f.rating||0));}
function rec(f){var r=R();return r.U.recordText?r.U.recordText(f.record||f):((f.record&&f.record.wins)||0)+'-'+((f.record&&f.record.losses)||0)+'-'+((f.record&&f.record.draws)||0);}
function country(id){var r=R();if(r.U.findCountry)return r.U.findCountry(id);return(r.D.countries||[]).find(function(c){return c&&c.id===id;})||{id:id,label:id||'—',flag:''};}
function countryHtml(id){var c=country(id),label=(c&&(c.label||c.name))||id||'—';var flag=c&&c.flag?'<img class="flag-icon" src="'+esc(c.flag)+'" alt="'+esc(label)+'">':'';return '<span class="country-label">'+flag+'<span>'+esc(label)+'</span></span>';}
function preview(state,offer){try{if(R().F.buildFightPreview&&offer&&offer.id)return R().F.buildFightPreview(state,offer.id);}catch(e){}return{};}
function money(v){return '$'+Math.round(Number(v)||0);}
function fightRow(state,offer){var op=byId(state,offer&&offer.opponentId);if(!op)return'';var p=preview(state,offer);var chance=p.winChance!=null?p.winChance:(offer.winChance!=null?offer.winChance:offer.chance);if(chance==null)chance='—';if(typeof chance==='number')chance=Math.round(chance)+'%';else if(String(chance).indexOf('%')===-1&&chance!=='—')chance=String(chance)+'%';var purse=p.purse!=null?p.purse:(offer.purse!=null?offer.purse:(offer.reward!=null?offer.reward:offer.money));var rating=p.opponentRating!=null?p.opponentRating:ovr(op);return '<div class="fw-fight-row"><button class="small-btn fighter-name-btn fw-tight-name" data-fighter="'+esc(op.id)+'">'+esc(nm(op))+'</button><span class="fw-chip fw-country">'+countryHtml(op.countryId||op.currentCountryId||op.homeCountryId)+'</span><span class="fw-chip fw-chance">Шанс '+esc(chance)+'</span><span class="fw-chip fw-money">'+esc(money(purse))+'</span><span class="fw-chip fw-ovr">OVR '+esc(rating)+'</span><button class="primary fw-fight-btn" data-preview-fight="'+esc(offer.id)+'">Бой</button></div>';}
function ensureAges(state){if(!state||!state.roster)return;var week=Number(state.week)||1;state.roster.forEach(function(f){if(!f)return;var age=Math.max(14,Number(f.age)||(f.isPlayer?18:20));if(!f.birthWeek){f.birthWeek=Math.max(1,week-age*48);f.birthYear=Math.floor((f.birthWeek-1)/48)+1;f.birthMonth=Math.floor(((f.birthWeek-1)%48)/4)+1;f.birthWeekOfMonth=((f.birthWeek-1)%4)+1;}f.age=Math.max(14,Math.floor((week-f.birthWeek)/48));f.birthdayLabel='год '+f.birthYear+', месяц '+f.birthMonth+', '+f.birthWeekOfMonth+' неделя';});}
function streetRating(state){if(!state||!state.roster)return;state.roster.forEach(function(f){if(!f||f.trackId!=='street')return;var r=f.record||{},total=(r.wins||0)+(r.losses||0)+(r.draws||0);var wr=total?((r.wins||0)+0.5*(r.draws||0))/total:0.5;f.streetRating=Math.round(ovr(f)*0.8+Math.round(wr*150)*0.2);});}
function proCadence(state){if(!state||!state.roster)return;var list=state.roster.filter(function(f){return f&&f.trackId==='pro'&&!f.retired;}).sort(function(a,b){return(ovr(b)+(b.record&&b.record.wins||0))-(ovr(a)+(a.record&&a.record.wins||0));});var total=Math.max(1,list.length-1);list.forEach(function(f,i){var t=i/total;var wait=Math.round(20-t*10);if(i<4)wait=20;else if(i<25)wait=15;else if(wait<10)wait=10;f.proFightIntervalWeeks=wait;if(!f.contractOpponentId&&!f.nextFightWeek)f.nextFightWeek=(Number(state.week)||1)+wait;});}
function repairTitles(state){if(!state||!state.roster||!R().D.weightClasses)return;state.titles=state.titles||{};['wbc','wba','wbo','ibf'].forEach(function(body){R().D.weightClasses.forEach(function(w){var id='pro_'+body+'_'+w.id,t=state.titles[id],champ=t&&byId(state,t.championId);if(champ&&!champ.retired)return;var pool=state.roster.filter(function(f){return f&&f.trackId==='pro'&&f.weightClassId===w.id&&!f.retired;}).sort(function(a,b){return ovr(b)-ovr(a);});if(pool[0])state.titles[id]=Object.assign(t||{},{id:id,trackId:'pro',countryId:'world',weightClassId:w.id,bodyId:body,label:body.toUpperCase(),championId:pool[0].id,active:true});});});}
function foreignOffers(state){if(!state||!state.offers)return;var p=byId(state,state.playerId);if(!p||p.trackId!=='amateur')return;var rank=p.amateurRankId||'';if(['ms','msmk'].indexOf(rank)===-1)return;if(state.offers.some(function(o){var f=byId(state,o.opponentId);return f&&f.countryId!==p.countryId;}))return;var pool=(state.roster||[]).filter(function(f){return f&&f.trackId==='amateur'&&f.weightClassId===p.weightClassId&&f.countryId!==p.countryId&&Math.abs(ovr(f)-ovr(p))<=18;});for(var i=0;i<Math.min(3,pool.length,state.offers.length);i++)state.offers[i].opponentId=pool[i].id;}
function tournamentXp(state){var m=state&&state.modal;if(!m||m.type!=='tournamentResult'||!m.session)return;var p=byId(state,state.playerId);if(!p)return;var key=[state.week,m.label,m.roundLabel,m.opponentName,m.result].join('|');if(state.__lastTournamentXpKey===key)return;state.__lastTournamentXpKey=key;var oppRating=Number(m.opponentRating)||0;var gain=m.result==='Победа'?Math.max(3,Math.round(3+(oppRating-ovr(p))/12)):2;p.trainingPoints=(Number(p.trainingPoints)||0)+gain;}
function mutate(state){forceVersion();ensureAges(state);streetRating(state);proCadence(state);repairTitles(state);foreignOffers(state);tournamentXp(state);}
function styles(){if(document.getElementById('fw-gameplay-238-style'))return;var s=document.createElement('style');s.id='fw-gameplay-238-style';s.textContent=['.top-pills,.player-strip{display:flex!important;gap:5px!important;align-items:center!important;flex-wrap:wrap!important}.top-pills .pill,.player-strip .pill,.top-pills .country-label,.player-strip .country-label{flex:0 0 auto!important;width:auto!important;max-width:max-content!important;white-space:nowrap!important}.fw-fight-list{display:grid!important;gap:6px!important;width:100%!important}.fw-fight-row{display:flex!important;align-items:center!important;gap:6px!important;width:100%!important;padding:5px 6px!important;border:1px solid rgba(255,255,255,.1)!important;border-radius:12px!important;background:rgba(255,255,255,.03)!important;white-space:nowrap!important;overflow-x:auto!important}.fw-fight-row>*{flex:0 0 auto!important}.fw-tight-name{width:auto!important;max-width:190px!important;min-width:0!important;padding:6px 10px!important;overflow:hidden!important;text-overflow:ellipsis!important}.fw-chip{display:inline-flex!important;align-items:center!important;gap:5px!important;width:auto!important;max-width:max-content!important;min-height:25px!important;padding:4px 8px!important;border-radius:999px!important;border:1px solid rgba(255,255,255,.11)!important;background:rgba(255,255,255,.045)!important;font-size:11px!important;line-height:1!important;white-space:nowrap!important}.fw-country,.flag-pill,.country-pill{width:auto!important;max-width:max-content!important;min-width:0!important}.fw-country .country-label,.flag-pill .country-label,.country-pill .country-label{display:inline-flex!important;width:auto!important;max-width:max-content!important;gap:5px!important;white-space:nowrap!important}.fw-country .country-label span{max-width:90px!important;overflow:hidden!important;text-overflow:ellipsis!important}.fw-chance{color:#b9d4ff!important;border-color:rgba(59,130,246,.35)!important}.fw-money,.fw-ovr{color:#f3d98d!important;border-color:rgba(214,160,25,.34)!important}.fw-fight-btn{width:auto!important;min-width:48px!important;padding:6px 10px!important;font-size:11px!important}.fight-line{display:none!important}.fw-inline-name{padding:3px 7px!important;min-height:0!important}@media(max-width:760px){.fw-fight-row{gap:5px!important;padding:4px!important}.fw-tight-name{max-width:120px!important}.fw-chip{font-size:10px!important;padding:4px 6px!important}.fw-country .country-label span{max-width:58px!important}}'].join('\n');document.head.appendChild(s);}
function patchFightRows(root,state){if(!state)return;var offers=(state.offers||[]).filter(function(o){return o&&!o.isCompetition&&o.opponentId;});var list=root.querySelector('.fight-lines,.offer-list.compact-offers.fight-lines,.offer-list.fight-lines');if(!list){if((state.selectedTab||'')!=='fights')return;var a=root.querySelector('.content-card');if(!a||!a.parentNode)return;list=document.createElement('div');a.parentNode.insertBefore(list,a.nextSibling);}list.className='fw-fight-list';list.innerHTML=offers.length?offers.map(function(o){return fightRow(state,o);}).join(''):'<div class="content-card"><div class="muted small">Пусто.</div></div>';}
function patchTournament(root){root.querySelectorAll('.tournament-modal .split-row,.modal .split-row').forEach(function(row){var text=row.textContent||'';if(/NPC|без игрока|AI/.test(text)&&!/Влад|Ты|player/i.test(text))row.remove();});}
function patchFav(root,state){if(!state)return;root.querySelectorAll('.favorite-list .split-row').forEach(function(row){var b=row.querySelector('button[data-fighter]');if(!b)return;var f=byId(state,b.dataset.fighter);if(!f)return;row.innerHTML='<button class="small-btn fighter-name-btn fw-tight-name" data-fighter="'+esc(f.id)+'">'+esc(nm(f))+'</button><span class="fw-chip fw-country">'+countryHtml(f.countryId)+'</span><span class="fw-chip fw-ovr">OVR '+ovr(f)+'</span><span class="fw-chip">'+esc(rec(f))+'</span>';});}
function patchNews(root,state){if(!state||!state.roster)return;var fighters=state.roster.slice().sort(function(a,b){return nm(b).length-nm(a).length;}).slice(0,1500);root.querySelectorAll('.news-inline-text').forEach(function(n){if(n.querySelector('button[data-fighter]'))return;var html=esc(n.textContent||'');fighters.forEach(function(f){var name=nm(f);if(!name||name.length<5)return;var safe=esc(name),rx=new RegExp('\\b'+safe.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')+'\\b','g');html=html.replace(rx,'<button class="small-btn fighter-name-btn fw-inline-name" data-fighter="'+esc(f.id)+'">'+safe+'</button>');});n.innerHTML=html;});}
function patchRender(){var Rr=window.FS&&window.FS.Render;if(!Rr||Rr.__gameplayFix238||typeof Rr.dashboard!=='function')return;Rr.__gameplayFix238=true;var old=Rr.dashboard.bind(Rr);Rr.dashboard=function(state){mutate(state);var t=document.createElement('template');t.innerHTML=old(state);styles();patchFightRows(t.content,state);patchTournament(t.content);patchFav(t.content,state);patchNews(t.content,state);return t.innerHTML;};}
window.FWGameplayFix238={version:VERSION,hardUpdate:hardUpdate};forceVersion();installUpdateFix();patchRender();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){forceVersion();installUpdateFix();styles();patchRender();});else{forceVersion();installUpdateFix();styles();patchRender();}window.addEventListener('load',function(){forceVersion();installUpdateFix();styles();patchRender();});setInterval(forceVersion,2000);
}());
