(function(){
"use strict";
var VERSION="update-button-hard-reset-2.3.7",SCHEMA=237;
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c];});}
function forceVersion(){window.FS=window.FS||{};window.FS.Data=window.FS.Data||{};window.FS.Data.appVersion=VERSION;window.FS.Data.saveSchemaVersion=SCHEMA;}
function isFwCache(k){var v=String(k||"").toLowerCase();return v.indexOf("fight")!==-1||v.indexOf("simulator")!==-1||v.indexOf("fw-")===0;}
function clearCaches(){if(!window.caches||!caches.keys)return Promise.resolve();return caches.keys().then(function(keys){return Promise.all(keys.map(function(k){return isFwCache(k)?caches.delete(k):false;}));});}
function unregisterSW(){if(!("serviceWorker" in navigator)||!navigator.serviceWorker.getRegistrations)return Promise.resolve();return navigator.serviceWorker.getRegistrations().then(function(regs){return Promise.all(regs.map(function(r){return r.unregister();}));});}
function hardReset(e){if(e){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();}forceVersion();Promise.resolve().then(unregisterSW).then(clearCaches).then(function(){location.replace("./reset-cache.html?fromUpdateButton=2.3.7&t="+Date.now());}).catch(function(){location.replace("./reset-cache.html?fromUpdateButton=2.3.7&t="+Date.now());});return false;}
function installUpdateButtonFix(){if(window.__fwUpdateButtonHardReset237)return;window.__fwUpdateButtonHardReset237=true;document.addEventListener("click",function(e){var b=e.target&&e.target.closest?e.target.closest(".update-now-btn,[data-action='force-update'],[data-update-now]"):null;if(b)hardReset(e);},true);window.FWHardUpdateNow237=hardReset;}
function refs(){window.FS=window.FS||{};return{U:window.FS.Utils||{},Fight:window.FS.Fight||{},Data:window.FS.Data||{}};}
function fighterById(state,id){var r=refs();if(!state||!id)return null;if(r.U.getFighterById)return r.U.getFighterById(state,id);return(state.roster||state.fighters||[]).find(function(f){return f&&f.id===id;})||null;}
function fighterName(f){return f?(f.name||f.fullName||((f.firstName||"")+" "+(f.lastName||f.surname||"")).trim()||"Боец"):"Боец";}
function recordText(f){var r=refs();if(!f)return"0-0-0";if(r.U.recordText)return r.U.recordText(f.record||f);var rec=f.record||f;return(rec.wins||0)+"-"+(rec.losses||0)+"-"+(rec.draws||0);}
function ovr(f){var r=refs();if(!f)return 0;if(r.U.statAverage)return r.U.statAverage(f.stats||f);return Math.round(Number(f.ovr||f.overall||f.rating||0));}
function countryById(id){var r=refs();if(r.U.findCountry)return r.U.findCountry(id);return(r.Data.countries||[]).find(function(c){return c&&c.id===id;})||{id:id,label:id||"—",flag:""};}
function countryHtml(id){var c=countryById(id),label=(c&&(c.label||c.name))||id||"—";var flag=c&&c.flag?'<img class="flag-icon" src="'+esc(c.flag)+'" alt="'+esc(label)+'">':"";return'<span class="country-label">'+flag+'<span>'+esc(label)+'</span></span>';}
function previewFor(state,offer){var r=refs();try{if(r.Fight.buildFightPreview&&offer&&offer.id)return r.Fight.buildFightPreview(state,offer.id);}catch(e){}return null;}
function money(v){return"$"+Math.round(Number(v)||0);}
function rowHtml(state,offer){var op=fighterById(state,offer&&offer.opponentId);if(!op)return"";var p=previewFor(state,offer)||{};var chance=p.winChance;if(chance==null)chance=offer.winChance;if(chance==null)chance=offer.chance;if(chance==null)chance="—";if(typeof chance==="number")chance=Math.round(chance)+"%";else if(String(chance).indexOf("%")===-1&&chance!=="—")chance=String(chance)+"%";var purse=p.purse;if(purse==null)purse=offer.purse;if(purse==null)purse=offer.reward;if(purse==null)purse=offer.money;var rating=p.opponentRating;if(rating==null)rating=ovr(op);return'<div class="fw-fight-row"><button class="small-btn fighter-name-btn fw-fight-name" data-fighter="'+esc(op.id)+'">'+esc(fighterName(op))+'</button><span class="fw-fight-cell fw-fight-record">'+esc(recordText(op))+'</span><span class="fw-fight-cell fw-fight-country">'+countryHtml(op.countryId||op.currentCountryId||op.homeCountryId)+'</span><span class="fw-fight-cell fw-fight-chance">Шанс '+esc(chance)+'</span><span class="fw-fight-cell fw-fight-money">'+esc(money(purse))+'</span><span class="fw-fight-cell fw-fight-ovr">OVR '+esc(rating)+'</span><button class="primary fw-fight-action" data-preview-fight="'+esc(offer.id)+'">Бой</button></div>';}
function patchFightRows(root,state){if(!root||!state)return;var list=root.querySelector(".fight-lines,.offer-list.compact-offers.fight-lines,.offer-list.fight-lines");var offers=(state.offers||[]).filter(function(o){return o&&!o.isCompetition&&o.opponentId;});if(!list){if(state.selectedTab!=="fights")return;var card=root.querySelector(".fights-head,.content-card");if(!card||!card.parentNode)return;list=document.createElement("div");card.parentNode.insertBefore(list,card.nextSibling);}list.className="fw-fight-list";list.innerHTML=offers.length?offers.map(function(o){return rowHtml(state,o);}).join(""):'<div class="content-card"><div class="muted small">Пусто.</div></div>';}
function injectStyles(){if(document.getElementById("fight-world-fight-rows-237-style"))return;var s=document.createElement("style");s.id="fight-world-fight-rows-237-style";s.textContent=[".fw-fight-list{display:grid!important;gap:6px!important;width:100%!important;min-width:0!important}",".fw-fight-row{display:flex!important;align-items:center!important;gap:7px!important;width:100%!important;min-height:36px!important;padding:5px 6px!important;border:1px solid rgba(255,255,255,.10)!important;border-radius:12px!important;background:rgba(255,255,255,.028)!important;white-space:nowrap!important;overflow-x:auto!important;overflow-y:hidden!important;-webkit-overflow-scrolling:touch!important}",".fw-fight-row>*{flex:0 0 auto!important}",".fw-fight-name{width:auto!important;max-width:210px!important;min-width:0!important;padding:6px 10px!important;justify-content:flex-start!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important}",".fw-fight-cell{display:inline-flex!important;align-items:center!important;justify-content:center!important;width:auto!important;min-height:27px!important;padding:5px 9px!important;border:1px solid rgba(255,255,255,.10)!important;border-radius:999px!important;background:rgba(255,255,255,.045)!important;color:var(--text,#f4f4f5)!important;font-size:11px!important;line-height:1!important}",".fw-fight-record{min-width:72px!important}",".fw-fight-country{min-width:118px!important;justify-content:flex-start!important}",".fw-fight-country .country-label{display:inline-flex!important;align-items:center!important;gap:5px!important;min-width:0!important}",".fw-fight-country .country-label span{max-width:96px!important;overflow:hidden!important;text-overflow:ellipsis!important}",".fw-fight-chance{min-width:74px!important;color:#b9d4ff!important;border-color:rgba(59,130,246,.34)!important}",".fw-fight-money{min-width:58px!important;color:#f3d98d!important;border-color:rgba(214,160,25,.34)!important}",".fw-fight-ovr{min-width:62px!important;color:#f3d98d!important;border-color:rgba(214,160,25,.34)!important}",".fw-fight-action{width:auto!important;min-width:50px!important;min-height:29px!important;padding:6px 10px!important;border-radius:10px!important;font-size:11px!important}",".fight-line{display:none!important}","@media(max-width:760px){.fw-fight-row{gap:5px!important;padding:4px 5px!important}.fw-fight-name{max-width:126px!important}.fw-fight-cell{font-size:10px!important;min-height:24px!important;padding:4px 6px!important}.fw-fight-country{min-width:82px!important}.fw-fight-country .country-label span{max-width:58px!important}.fw-fight-record{min-width:58px!important}.fw-fight-chance{min-width:62px!important}.fw-fight-money{min-width:48px!important}.fw-fight-ovr{min-width:52px!important}.fw-fight-action{min-height:26px!important;padding:4px 8px!important}}"].join("\n");document.head.appendChild(s);}
function patchRender(){var R=window.FS&&window.FS.Render;if(!R||R.__fightRowsFix237||typeof R.dashboard!=="function")return;R.__fightRowsFix237=true;var old=R.dashboard.bind(R);R.dashboard=function(state){var t=document.createElement("template");t.innerHTML=old(state);forceVersion();injectStyles();patchFightRows(t.content,state);return t.innerHTML;};}
forceVersion();installUpdateButtonFix();window.FWFix237={version:VERSION,applyHardUpdateNow:hardReset,patchFightRows:patchFightRows,clearFightCaches:clearCaches,unregisterServiceWorkers:unregisterSW};patchRender();
if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",function(){forceVersion();injectStyles();patchRender();installUpdateButtonFix();});}else{forceVersion();injectStyles();patchRender();installUpdateButtonFix();}
window.addEventListener("load",function(){forceVersion();injectStyles();patchRender();installUpdateButtonFix();});setInterval(forceVersion,2000);
}());
